test deduplication for non exact matches + more laxist duplication criteria
QwantResearch/addresses-importer pull request #23
Opened 2020-02-10 13:42 UTC by remi-dupre

Add a few handmade test of addresses with non trivial duplication.

### Criterion change

I also suggested a new change to the duplication criteria. If two addresses are less than 10 meters apart from each other, then the criterion is less strict about street name similarity, this appears to help libpostal with these two cases:

 - removal of articles like in "Avenue du Général Leclerc" <-> "Avenue Général Leclerc"
 - name variations: "route" <-> "rue"

2020-02-10 14:11 UTC, GuillaumeGomez approved these changes

2020-02-10 14:27 UTC, GuillaumeGomez requested changes

2020-02-10 14:27 UTC, GuillaumeGomez commented on deduplicator/src/tests.rs
> +const DB_WITH_DUPES: &str = "data/tests/with_dupes.sql";
Just realized this is only used in test. It therefore has nothing to do in here.

2020-02-10 14:31 UTC, GuillaumeGomez approved these changes
All good!

2020-02-13 17:29 UTC, amatissart approved these changes

2020-02-13 17:32 UTC, merged