Add dockerfile
QwantResearch/addresses-importer pull request #34
Opened 2020-02-12 16:34 UTC by GuillaumeGomez

2020-02-13 17:20 UTC, remi-dupre requested changes
When building the image, it appears that docker starts by loading all content of current directory. It would be helpful to skip large files that could appear in dev workflow by adding a `.dockerignore`:

```
**/addresses.db
**/target
```

2020-02-13 17:20 UTC, remi-dupre commented on Dockerfile
> +ENV CC "gcc-4.8"
Do we need to freeze a compiler version? (I don't know about C usages, but I often see this, I guess there is a reason?)

2020-02-13 17:20 UTC, remi-dupre commented on Dockerfile
> +RUN apt-get update && apt-get install -y gcc-4.8 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
Some [libpostal dependancies](https://github.com/openvenues/libpostal#installation-maclinux) appear to be missing from the docker image. Be careful as I think libpostal omitted `libgeos` in its dependancies.

2020-02-13 17:20 UTC, remi-dupre commented on Dockerfile
> +    && cd postal \
```suggestion
    && cd libpostal \
```

2020-02-13 17:20 UTC, remi-dupre commented on Dockerfile
> +    && make install \
I didn't know that `make install` triggers a build :)

Maybe we still want to explicitly run a `make -jX` (X = 4?) to speed things up?

2020-02-13 17:20 UTC, remi-dupre commented on Dockerfile
> +COPY --from=builder /srv/addresses-importer/deduplicator/target/release/deduplicator /usr/bin/deduplicator
If I understand well, we are now exporting necessary files in a newly created docker image. Won't we miss a part of dependencies here? At least libpostal and its metadata and some of its dependencies?

2020-02-13 17:20 UTC, remi-dupre commented on Dockerfile
> +RUN apt-get update && apt-get install -y gcc-4.8 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
Why do we need `gcc` in the final image?

2020-02-14 09:19 UTC, GuillaumeGomez commented on Dockerfile
> +ENV CC "gcc-4.8"
This is what is being used for compiling gcc. So maybe not necessary but not sure either...

2020-02-14 16:57 UTC, GuillaumeGomez commented
Needs to add libgeos dependency to finish the deduplicator build.

2020-02-17 15:51 UTC, remi-dupre commented on Dockerfile
> +    && cp /usr/local/lib/libpostal.so .
Is this copy used? (A symlink would also probably be better)

2020-02-17 16:34 UTC, remi-dupre approved these changes

2020-02-17 16:34 UTC, remi-dupre commented on Dockerfile
> +ENV DEBIAN_FRONTEND noninteractive
I think this environment variable is already relevant when `apt` is run (avoiding asking for any input by using defaults everywhere):

https://askubuntu.com/questions/972516/debian-frontend-environment-variable#972528

2020-02-18 16:06 UTC, amatissart approved these changes

2020-02-18 16:08 UTC, merged